version: "3"
services:
  query:
    image: "{{ salt['pillar.get']('jibjib:lookup:query:image') }}"
    container_name: "{{ salt['pillar.get']('jibjib:lookup:query:container_name') }}"
    ports:
      - "{{ salt['pillar.get']('jibjib:lookup:query:host_port') }}:8081"
    environment:
      - SERVING_URL=serving
      - SERVING_PORT={{ salt['pillar.get']('jibjib:lookup:serving:host_port') }}
    volumes:
      - "{{ salt['pillar.get']('jibjib:lookup:query:dir') }}/input:/app/input"
    restart: always
    command: gunicorn -w 5 -b 0.0.0.0:8081 --max-requests 10 --preload wsgi
    depends_on:
      - serving
  
  serving:
    image: "{{ salt['pillar.get']('jibjib:lookup:serving:image') }}"
    container_name: "{{ salt['pillar.get']('jibjib:lookup:serving:container_name') }}"
    ports: 
      - "{{ salt['pillar.get']('jibjib:lookup:serving:host_port') }}:{{ salt['pillar.get']('jibjib:lookup:serving:host_port') }}"
    volumes:
      - "{{ salt['pillar.get']('jibjib:lookup:serving:dir') }}/serve:{{ salt['pillar.get']('jibjib:lookup:serving:dir') }}"
    restart: always
    command: tensorflow_model_server --port={{ salt['pillar.get']('jibjib:lookup:serving:host_port') }} --model_name={{ salt['pillar.get']('jibjib:lookup:serving:model_name') }} --model_base_path={{ salt['pillar.get']('jibjib:lookup:serving:dir') }}/{{ salt['pillar.get']('jibjib:lookup:serving:model_name') }}