version: "3"
services:
  query:
    image: "{{ salt['pillar.get']('jibjib:lookup:query:image') }}"
    container_name: "{{ salt['pillar.get']('jibjib:lookup:query:container_name') }}"
    ports:
      - "{{ salt['pillar.get']('jibjib:lookup:query:host_port') }}:8081"
    restart: always
    command: python app.py