version: '3.1'
services:
  mongo:
    image: "{{ salt['pillar.get']('jibjib:lookup:db:image') }}"
    container_name: {{ salt['pillar.get']('jibjib:lookup:db:container_name') }}
    volumes:
        - "./data:/data/db"
        - "./conf:/etc/mongo"
    ports:
        - {{ salt['pillar.get']('jibjib:lookup:db:host_port') }}:27017
    restart: always
    command: --config /etc/mongo/mongod.conf --auth
